### ISSUE TITLE
Cannot connect to my pc

### ISSUE THREAD

**Issue by metalex201** [shrimqy/Sekia#2]
both devices are on the same network, host is running on windows 11 and the client is running on Xiaomi hyperOS (android 13)
 
 I have all permissions allowed, my pc appears in the app but when i connect nothing happens.
 
 heres the error log, I got through logcat

![image](https://github.com/user-attachments/assets/4924220f-b8b1-4962-9e20-0c6a9bc36c1d)

**Comment by shrimqy** [comment]
Ok, I figured out the issue but in the mean time you can just keep refreshing it until the device finally shows.
It was minor bug related to how I saved the devices information, this didn't happen before. I will try to fix it in the next update.

**Comment by metalex201** [comment]
> Ok, I figured out the issue but in the mean time you can just keep refreshing it until the device finally shows. It was minor bug related to how I saved the devices information, this didn't happen before. I will try to fix it in the next update.

refreshing after connecting still has the same issue where it doesnt connect, maybe this is a network issue on my side?


https://github.com/user-attachments/assets/734c1b3b-6aa5-4c1a-b122-362dc5c54ea5

**Comment by metalex201** [comment]
i tried connecting on an emulator and it worked, this is definetly an issue whit my phone and not the app, probably some limitation made by xiaomi hyperOS

**Comment by metalex201** [comment]
another thing i noticed is this

![image](https://github.com/user-attachments/assets/b1953d0c-d7f9-4069-a48d-9ff7a0b8ec80)

**Comment by shrimqy** [comment]
> i tried connecting on an emulator and it worked, this is prpo an issue whit my phone and not the app, probably some limitation made by xiaomi hyperOS

**Comment by shrimqy** [comment]
> another thing i noticed is this

This is fine, i couldn't think of a way to skip trying to connect to the server multiple times when discovering multiple services which there isn't. I dare say it is a weird android bug.

**Comment by metalex201** [comment]
> > i tried connecting on an emulator and it worked, this is prpo an issue whit my phone and not the app, probably some limitation made by xiaomi hyperOS
> 
> I see, can you check if the IP you're trying to connect is correct? Check it by Typing "ipconfig / all" in cmd.
> 
> The discovery and connection basically on two things, Your pc broadcasts an mDNS much like printers and other devices do so that android can detect them with network manager api. After which we will use the ip from the service and try to connect with the pc. If the local ip your pc is providing the app is a different than the one with which we are making the server it won't work i assume but that shouldn't be an issue since I have considered that as well when making the server connection.
> 
> I will try to investigate this issue, I think making a manual way of connecting is also a good fallback option have.

found the issue, i had a virtual Ethernet adapter for VirtualBox, for some odd reason Seki was using the ip of that virtual adapter instead of the main one, It connects correctly now and works as expected, thanks for the help!

**Comment by shrimqy** [comment]
> > > i tried connecting on an emulator and it worked, this is prpo an issue whit my phone and not the app, probably some limitation made by xiaomi hyperOS
> > 
> > 
> > I see, can you check if the IP you're trying to connect is correct? Check it by Typing "ipconfig / all" in cmd.
> > The discovery and connection basically on two things, Your pc broadcasts an mDNS much like printers and other devices do so that android can detect them with network manager api. After which we will use the ip from the service and try to connect with the pc. If the local ip your pc is providing the app is a different than the one with which we are making the server it won't work i assume but that shouldn't be an issue since I have considered that as well when making the server connection.
> > I will try to investigate this issue, I think making a manual way of connecting is also a good fallback option have.
> 
> found the issue, i had a virtual Ethernet adapter for VirtualBox, for some odd reason Seki was using the ip of that virtual adapter instead of the main one, I removed that adapter from windows and now it connects correctly and works as expected, thanks for the help!

ok good im glad that worked, I should consider coming up with a different of getting the Ip. Thank you.
